markdown: rdiscount
permalink: /:title/
url: http://ruoshuisanqian.github.io
highlighter: pygments
name: 独孤小新
description: 独孤小新 呆萌android猿.
author: wanglixin
email: wang_lx@yeah.net
safe: true
duoshuo: ruoshuisanqian
hub: ruoshuisanqian
paginate: 100
about: "弱菜一枚。"
